categories: [ChIP-seq]
name: manorm
description: "MAnorm: A robust model for quantitative comparison of ChIP-Seq data sets"
long_description:
  ChIP-Seq is widely used to characterize genome-wide binding patterns of transcription factors
  and other chromatin-associated proteins. Although comparison of ChIP-Seq data sets is critical for
  understanding cell type-dependent and cell state-specific binding, and thus the study of cell-specific
  gene regulation, few quantitative approaches have been developed.

  Here, we present a simple and effective method, MAnorm, for quantitative comparison of ChIP-Seq data sets
  describing transcription factor binding sites and epigenetic modifications. The quantitative binding differences
  inferred by MAnorm showed strong correlation with both the changes in expression of target genes and the binding
  of cell type-specific regulators.
owner: haydensun
homepage_url: https://github.com/shao-lab/MAnorm
remote_repository_url: https://github.com/shao-lab/MAnorm/tree/master/galaxy-tool
type: unrestricted
